tealcrm/dashboard/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
]

tealcrm/lead/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.leads_list, name='leads_list'),
    path('<int:pk>/', views.leads_detail, name='leads_detail'),
    path('add-lead/', views.add_lead, name='add_lead'),
]

tealcrm/tealcrm/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about
from userprofile.views import signup

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads', include('lead.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/', about, name='about'),
    path('sign-up/', signup, name='signup'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html'), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

tealcrm/lead/models.py
from django.contrib.auth.models import User
from django.db import models


class Lead(models.Model):
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    CHOICES_PRIORITY = (
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High'),
    )

    NEW = 'new'
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'

    CHOICES_STATUS = (
        (NEW, 'New'),
        (CONTACTED, 'Contacted'),
        (WON, 'Won'),
        (LOST, 'Lost'),
    )

    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    created_by = models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    

tealcrm/userprofile/models.py
from django.contrib.auth.models import User
from django.db import models


class Userprofile(models.Model):
    name = models.OneToOneField(User, related_name="userprofile", on_delete=models.CASCADE)

tealcrm/lead/forms.py
from django import forms

from .models import Lead

class AddLeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ('name', 'email', 'description', 'priority', 'status',)

tealcrm/core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html')


def about(request):
    return render(request, 'core/about.html')

tealcrm/dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required
def dashboard(request):
    return render(request, 'dashboard/dashboard.html')

tealcrm/lead/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from .forms import AddLeadForm
from .models import Lead


@login_required
def leads_list(request):
    leads = Lead.objects.filter(created_by=request.user)

    return render(request, 'lead/leads_list.html', {'leads':leads})


@login_required
def leads_detail(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    # lead = Lead.objects.filter(created_by=request.user).get(pk=pk)

    return render(request, 'lead/leads_detail.html', {'lead': lead})


@login_required
def add_lead(request):
    if request.method == "POST":
        form = AddLeadForm(request.POST)

        if form.is_valid():
            lead = form.save(commit=False)
            lead.created_by = request.user
            lead.save()

            return redirect('dashboard')

    else:
        form = AddLeadForm()

    return render(request, 'lead/add_lead.html', {'form': form})

tealcrm/userprofile/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

from .models import Userprofile


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            user = form.save()

            Userprofile.objects.create(user=user)

            return redirect('log-in/')
    else:
        form = UserCreationForm()

    return render(request, 'userprofile/signup.html', {
        'form': form
    })

tealcrm/core/templates/core/about.html
{% extends "core/base.html" %}

{% block title %}about{% endblock %}

{% block content %}
    <p>This is the about page</p>
{% endblock %}

tealcrm/core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %}</title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between bg-teal-500">
            <a href="/" class="text-white">Teal CRM</a>

            <div class="space-x-4">
                <a href="{% url 'about' %}" class="text-white">About</a>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'dashboard' %}" class="py-4 px-6 bg-teal-600 rounded-xl text-white">Dashboard</a>
                    <a href="{% url 'leads_list' %}" class="py-4 px-6 bg-teal-600 rounded-xl text-white">Leads</a>
                    <a href="{% url 'logout' %}" class="py-4 px-6 bg-red-600 rounded-xl text-white">Log out</a>
                {% else %}
                    <a href="{% url 'login' %}" class="py-4 px-6 bg-teal-600 rounded-xl text-white">Log in</a>
                    <a href="{% url 'signup' %}" class="py-4 px-6 bg-teal-300 rounded-xl text-white">Sign up</a>
                {% endif %}
            </div>
        </nav>

        {% block content %}
        {% endblock %}

        <footer class="py-8 text-center bg-gray-200">
            <p class="text-xs text-gray-700">Copyright (c) 2024 - Teal CRM</p>
        </footer>
    </body>

</html>

tealcrm/core/templates/core/index.html
{% extends "core/base.html" %}

{% block title %}Teal CRM{% endblock %}

{% block content %}
    <p>This front page</p>
{% endblock %}

tealcrm/dashboard/templates/dashboard/dashboard.html
{% extends 'core/base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <h1 class="text-xl">Dashboard</h1>
{% endblock %}

tealcrm/lead/templates/lead/add_lead.html
{% extends 'core/base.html' %}

{% block title %}Add lead{% endblock %}

{% block content %}
    <div class="px-6 py-6">
        <h1 class="text-xl">Add lead</h1>

        <form method="post" action=".">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
        </forms>
    </div>
{% endblock %}

tealcrm/lead/templates/lead/leads_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ lead.name }}{% endblock %}

{% block content %}
    <div class="px-6 py-6">
        
        <h1 class="mb-4 text-xl">{{ lead.name }}</h1>

        {% if lead.description %}

            <p class='font-semibold'>Name</p>
            <p class='mb-2'>{{ lead.description }}</p>
        {% endif %}

        <p class='font-semibold'>Priority</p>
        <p class='mb-2'>{{ lead.get_priority_display }}</p>

        <p class='font-semibold'>Status</p>
        <p>{{ lead.get_status_display }}</p>

        <p class='font-semibold'>Created at</p>
        <p class='mb-2'>{{ lead.created_at }}</p>

        <p class='font-semibold'>Modified at</p>
        <p class='mb-6'>{{ lead.modified_at }}</p>

        <a href="{% url 'leads_list' %}">Back to leads</a>
    </div>
{% endblock %}

tealcrm/lead/templates/lead/leads_list.html
{% extends 'core/base.html' %}

{% block title %}Leads{% endblock %}

{% block content %}
    <div class="px-6 py-6">
        
        <h1 class="mb-4 text-xl">Leads</h1>

        <a href="{% url 'add_lead' %}" class="inline-block py-4 px-6 bg-teal-600 rounded-xl text-white">Add lead</a>

        <div class='mt-6 flex justify-between'>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Priority</p>
            <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Status</p>
        </div>

        {% for lead in leads %}
            <div class='flex justify-between'>
                <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                    <a href="{% url 'leads_detail' lead.id %}">{{ lead.name }}</a>
                </p>
                <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                    {{ lead.get_priority_display }}
                </p>
                <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                    {{ lead.get_status_display }}
                </p>
            </div>
        {% endfor %}

    </div>
{% endblock %}

tealcrm/userprofile/templates/userprofile/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
    <h1 class="text-xl">Log in</h1>
    <form method="post" action=".">

        {% csrf_token %}

        {{ form.as_p }}

        <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
    </form>
{% endblock %}

tealcrm/userprofile/templates/userprofile/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
    <h1 class="text-xl">Sing up</h1>
    <form method="post" action=".">

        {% csrf_token %}

        {{ form.as_p }}

        <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
    </form>
{% endblock %}